# Generated by Django 3.1.4 on 2021-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getboq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('B', 'Wall'), ('F', 'Floor'), ('G', 'Ceiling'), ('T', 'Panel')], default=None, max_length=20)),
                ('material', models.CharField(choices=[('01', 'Ceramic'), ('02', 'Plaster'), ('03', 'Stone'), ('04', 'Wood')], default=None, max_length=20)),
                ('schedule', models.BooleanField(default=False, verbose_name='Metraja Girsin mi?')),
            ],
        ),
    ]
