# Generated by Django 3.1.4 on 2021-01-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='setboq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Wall Core'), ('B', 'Wall Finish'), ('C', 'Storefront(Glazed Partition)'), ('D', 'Door'), ('E', 'Profile / Skirting'), ('F', 'Floor Finish'), ('G', 'Ceiling Finish'), ('H', 'Ceiling Bulkhead'), ('I', 'Casework'), ('J', 'Conveying'), ('K', 'Speciality Equipment'), ('L', 'Landscape'), ('M', 'Multi Leveled Facade System (Curtain Wall)'), ('N', 'Roof Covering'), ('O', 'Roof Soffit / Fascia'), ('P', 'Plumbing Fixture'), ('Q', 'Parking'), ('R', 'Railing'), ('S', 'Stair Finish'), ('T', 'Panel'), ('U', 'Mullion'), ('V', 'Generic Model'), ('W', 'Window'), ('X', 'Fixed Furniture'), ('Y', 'Movable Furniture'), ('Z', 'Special Construction')], default=None, max_length=20)),
                ('material', models.CharField(choices=[(1, 'Autoclaved Aerated Concrete Unit Masonry'), (2, 'Gypsum Plaster'), (3, 'Paint'), (4, 'Fabric'), (5, 'Drywall'), (6, 'Concrete Topping'), (7, 'Flooring Treatment'), (8, 'Dampproofing and Waterproofing'), (9, 'Acoustic Insulation'), (10, 'Thermal Protection'), (11, 'Weather Barriers'), (12, 'Ceramic'), (13, 'Concrete'), (14, 'Rubber'), (15, 'Granite'), (16, 'PVC'), (17, 'Wood'), (18, 'Terrazzo'), (19, 'Cement'), (20, 'Epoksi'), (21, 'Vapor'), (22, 'Bims'), (23, 'Acoustic Mineral Fiber'), (24, 'Acoustic Mineral Wool'), (25, 'Metal'), (26, 'Aluminyum Composite'), (27, 'Glazing'), (28, 'Natural Stone'), (29, 'Asphalt'), (31, 'Sand'), (32, 'Grass'), (33, 'Hafriyat'), (34, 'Subgrade Of Asphalt'), (35, 'Floor for Disabled'), (36, 'Site Elements'), (37, 'Brick'), (38, 'Satin Plaster')], default=None, max_length=20, verbose_name='Material or Type')),
                ('schedulein', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=None, max_length=20, null=True, verbose_name='will It Count?')),
                ('schtype', models.CharField(choices=[('C', 'Piece'), ('L', 'length'), ('V', 'Volume'), ('A', 'Area'), ('W', 'Weight')], default=None, max_length=20, null=True)),
                ('boqdescription', models.TextField(verbose_name='BoQ Description')),
                ('boqcodes', models.CharField(default=None, max_length=20)),
                ('objecttype', models.CharField(choices=[('Family', 'Family'), ('Material', 'Material')], default=None, max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('project', models.CharField(choices=[('IUA', 'IUA')], default=None, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
