# Generated by Django 3.1.4 on 2021-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setboq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setboq',
            name='material',
            field=models.CharField(choices=[('1', 'Autoclaved Aerated Concrete Unit Masonry'), ('2', 'Gypsum Plaster'), ('3', 'Paint'), ('4', 'Fabric'), ('5', 'Drywall'), ('6', 'Concrete Topping'), ('7', 'Flooring Treatment'), ('8', 'Dampproofing and Waterproofing'), ('9', 'Acoustic Insulation'), ('10', 'Thermal Protection'), ('11', 'Weather Barriers'), ('12', 'Ceramic'), ('13', 'Concrete'), ('14', 'Rubber'), ('15', 'Granite'), ('16', 'PVC'), ('17', 'Wood'), ('18', 'Terrazzo'), ('19', 'Cement'), ('20', 'Epoksi'), ('21', 'Vapor'), ('22', 'Bims'), ('23', 'Acoustic Mineral Fiber'), ('24', 'Acoustic Mineral Wool'), ('25', 'Metal'), ('26', 'Aluminyum Composite'), ('27', 'Glazing'), ('28', 'Natural Stone'), ('29', 'Asphalt'), ('31', 'Sand'), ('32', 'Grass'), ('33', 'Hafriyat'), ('34', 'Subgrade Of Asphalt'), ('35', 'Floor for Disabled'), ('36', 'Site Elements'), ('37', 'Brick'), ('38', 'Satin Plaster')], default=None, max_length=20, verbose_name='Material or Type'),
        ),
    ]
