# Generated by Django 3.1.4 on 2021-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setboq', '0002_auto_20210107_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setboq',
            name='category',
            field=models.CharField(choices=[('A', 'A:Wall Core'), ('B', 'B:Wall Finish'), ('C', 'C:Storefront(Glazed Partition)'), ('D', 'D:Door'), ('E', 'E:Profile / Skirting'), ('F', 'F:Floor Finish'), ('G', 'G:Ceiling Finish'), ('H', 'H:Ceiling Bulkhead'), ('I', 'I:Casework'), ('J', 'J:Conveying'), ('K', 'K:Speciality Equipment'), ('L', 'L:Landscape'), ('M', 'M:Multi Leveled Facade System (Curtain Wall)'), ('N', 'N:Roof Covering'), ('O', 'O:Roof Soffit / Fascia'), ('P', 'P:Plumbing Fixture'), ('Q', 'Q:Parking'), ('R', 'R:Railing'), ('S', 'S:Stair Finish'), ('T', 'T:Panel'), ('U', 'U:Mullion'), ('V', 'V:Generic Model'), ('W', 'W:Window'), ('X', 'X:Fixed Furniture'), ('Y', 'Y:Movable Furniture'), ('Z', 'Z:Special Construction')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='setboq',
            name='material',
            field=models.CharField(choices=[('01', '01:Autoclaved Aerated Concrete Unit Masonry'), ('02', '02:Gypsum Plaster'), ('03', '03:Paint'), ('04', '04:Fabric'), ('05', '05:Drywall'), ('06', '06:Concrete Topping'), ('07', '07:Flooring Treatment'), ('08', '08:Dampproofing and Waterproofing'), ('09', '09:Acoustic Insulation'), ('10', '10:Thermal Protection'), ('11', '11:Weather Barriers'), ('12', '12:Ceramic'), ('13', '13:Concrete'), ('14', '14:Rubber'), ('15', '15:Granite'), ('16', '16:PVC'), ('17', '17:Wood'), ('18', '18:Terrazzo'), ('19', '19:Cement'), ('20', '20:Epoksi'), ('21', '21:Vapor'), ('22', '22:Bims'), ('23', '23:Acoustic Mineral Fiber'), ('24', '24:Acoustic Mineral Wool'), ('25', '25:Metal'), ('26', '26:Aluminyum Composite'), ('27', '27:Glazing'), ('28', '28:Natural Stone'), ('29', '29:Asphalt'), ('31', '31:Sand'), ('32', '32:Grass'), ('33', '33:Hafriyat'), ('34', '34:Subgrade Of Asphalt'), ('35', '35:Floor for Disabled'), ('36', '36:Site Elements'), ('37', '37:Brick'), ('38', '38:Satin Plaster')], default=None, max_length=20, verbose_name='Material or Type'),
        ),
    ]
