# Generated by Django 3.1.4 on 2021-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setboq', '0003_auto_20210108_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setboq',
            name='material',
            field=models.CharField(choices=[('01', '01:Bims'), ('02', '02:Gypsum Plaster'), ('03', '03:Paint'), ('04', '04:Fabric'), ('05', '05:Drywall'), ('06', '06:Concrete Topping'), ('07', '07:Flooring Treatment'), ('08', '08:Dampproofing and Waterproofing'), ('09', '09:Acoustic Insulation'), ('10', '10:Thermal Protection'), ('11', '11:Weather Barriers'), ('12', '12:Ceramic'), ('13', '13:Concrete'), ('14', '14:Rubber'), ('15', '15:Granite'), ('16', '16:PVC'), ('17', '17:Wood'), ('18', '18:Terrazzo'), ('19', '19:Cement'), ('20', '20:Epoksi'), ('21', '21:Vapor'), ('22', '22:Autoclaved Aerated Concrete Unit Masonry'), ('23', '23:Acoustic Mineral Fiber'), ('24', '24:Acoustic Mineral Wool'), ('25', '25:Metal'), ('26', '26:Aluminyum Composite'), ('27', '27:Glazing'), ('28', '28:Natural Stone'), ('29', '29:Asphalt'), ('31', '31:Sand'), ('32', '32:Grass'), ('33', '33:Hafriyat'), ('34', '34:Subgrade Of Asphalt'), ('35', '35:Floor for Disabled'), ('36', '36:Site Elements'), ('37', '37:Brick'), ('38', '38:Satin Plaster')], default=None, max_length=20, verbose_name='Material or Type'),
        ),
    ]
