# Generated by Django 3.1.4 on 2021-01-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setboq', '0004_auto_20210108_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setboq',
            options={'ordering': ['boqcodes']},
        ),
    ]
