# Generated by Django 3.1.4 on 2021-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setboq', '0005_auto_20210108_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setboq',
            name='boqcodes',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
